## Упражнения по библиотеке Numpy

In [117]:
import numpy as np
from scipy import spatial
import math
import time


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

**2.** Заменить максимальный элемент случайного массива на 0

In [119]:
arr[np.argmax(arr)] = 0
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9,  0])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [121]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [122]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например стр|ока [2,2,3] остается, строка [3,3,3] удаляется)

In [123]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 1 1]
 [1 2 0]
 [1 0 3]
 [2 2 2]
 [4 1 3]
 [3 0 0]
 [2 4 3]
 [3 4 1]
 [2 3 3]
 [4 1 1]]
[[0 1 1]
 [1 2 0]
 [1 0 3]
 [4 1 3]
 [3 0 0]
 [2 4 3]
 [3 4 1]
 [2 3 3]
 [4 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [34]:
Z = np.random.randint(0, 2, (6,3))
print(Z)
print(np.unique(Z, axis=0))

[[0 0 0]
 [0 0 1]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [124]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
mul = 1
for i in range(len(X[0])):
    if X[i][i] != 0:
        mul *= X[i][i]
print(mul)

3


In [125]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
Y = X.diagonal()
Y[Y != 0].prod()


3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [126]:
def equal_multiset(a, b):
    a.sort()
    b.sort()
    return a == b

equal_multiset([1, 2, 2, 4], [2, 4, 1, 2])

True

In [128]:
def equal_multiset_np(a, b):
    a.sort()
    b.sort()
    return np.array_equal(a, b)
x = np.array([1, 2, 2, 4])
y = np.array([2, 4, 1, 2])    
equal_multiset_np(x, y)

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [129]:
def max_before_null(a: list):
    after_zero = [a[i] for i in range(1, len(a)) if a[i-1] == 0]
    return max(after_zero)
def max_before_null_np(a):
    zero = x==0
    return  x[1:][zero[:-1]].max()


x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max_before_null(list(x)))
print(max_before_null_np(x))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [130]:
def encode(a):
    a = list(a)
    r1 = []
    r2 = []
    count = 1
    for i in range(1, len(a)):

        if a[i] == a[i-1]:
            count += 1 
            if i == len(a) -1:
                r1.append(a[i-1])
                r2.append(count)
        else:
            r1.append(a[i-1])
            r2.append(count)
            count = 1
            if i == len(a) -1:
                r1.append(a[i])
                r2.append(count)
    

    result = (np.array(r1), np.array(r2))
    return result

In [131]:
def encode_np(a):
    d = np.ediff1d(a, to_begin=1, to_end=len(a))
    ix = np.arange(len(a)+1)[ d != 0 ]
    return a[ix[:-1]], np.diff(ix)
    

In [132]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
print(encode(x))
print(encode_np(x))

(array([2, 3, 5]), array([3, 3, 1]))
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [133]:
def distance(x, y):
    squares = [(x[i] - y[i])**2 for i in range(len(x))]
    return math.sqrt(sum(squares))
def distance_matrix(a, b):
    res = [[] for i in range(len(a))]
    i = 0
    for a_i in a:
        for b_i in b:
            res[i].append(distance(a_i, b_i))
        i += 1
    return res

In [134]:
def distance_matrix_np(a, b):
    P = np.add.outer(np.sum(a**2, axis=1), np.sum(b**2, axis=1))
    N = np.dot(a, b.T)
    return np.sqrt(P - 2*N)

In [136]:

a = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 7]])
b = np.array([[3, 4, 5], [1, 2, 3], [4, 5, 8]])
start_time = time.time()
print(spatial.distance.cdist(a, b))
print ("spatial.distance.cdist", time.time() - start_time )
start_time = time.time()
print(distance_matrix(list(a), list(b)))
print ("distance_matrix", time.time() - start_time)
start_time = time.time()
print(distance_matrix_np(a, b))
print ("distance_matrix_np", time.time() - start_time)

[[3.46410162 0.         6.55743852]
 [1.73205081 1.73205081 4.89897949]
 [3.46410162 6.92820323 1.73205081]]
spatial.distance.cdist 0.0013751983642578125
[[3.4641016151377544, 0.0, 6.557438524302], [1.7320508075688772, 1.7320508075688772, 4.898979485566356], [3.4641016151377544, 6.928203230275509, 1.7320508075688772]]
distance_matrix 0.00028705596923828125
[[3.46410162 0.         6.55743852]
 [1.73205081 1.73205081 4.89897949]
 [3.46410162 6.92820323 1.73205081]]
distance_matrix_np 0.0007479190826416016


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [137]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [138]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [139]:
average_calories = np.average(calorie_stats)
print("Difference with average calories: ", average_calories)

Difference with average calories:  106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [140]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [141]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [142]:
np.percentile(calorie_stats, 4)

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [143]:
more_calories = calorie_stats[calorie_stats > 60].shape[0]/calorie_stats.shape[0]* 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [144]:
calorie_std = calorie_stats.std()
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.